#!/bin/sh

IGNORE_RE="(update|downdate|README|\.git/$)"
FILES=$(find . -type f | egrep -v  "$IGNORE_RE")

cd $HOME/.ocd

for file in $FILES;do
  printf .
  dst="$file"
  src="$HOME/$file"
  if [ -f $src ];then
    chmod +w $dst
    cp $src $dst
  fi
done

echo " All Done!"
