#!/usr/bin/env bash

set -eu -o pipefail

ARCHIVE_NAME="gitignore_ocd.gz"

echo "[*] Fetching comprehensive gitignore lists from Toptal..."
echo ""

# Create the gitignore file with a header comment
{
  echo "# Generated by OCD <https://github.com/nycksw/ocd>"
  echo "# Data from <https://docs.gitignore.io/install/command-line>"
  echo "# Generated on: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
  echo ""

  # Get all available lists
  ALL_LISTS=$(curl -sL https://www.toptal.com/developers/gitignore/api/list \
    | xargs | sed 's/ /,/g')

  # Fetch and process the gitignore data; requires stripping some malformed comments.
  curl -fsSL "https://www.toptal.com/developers/gitignore/api/$ALL_LISTS" \
    | sed 's/^ *[\*\\\/]*//g' \
    | cat -s
} | gzip -9 -f > $ARCHIVE_NAME

file -i $ARCHIVE_NAME
ls -lh $ARCHIVE_NAME

echo ""
echo "[*] Successfully created gitignore_ocd.gz"
echo "This file can now be committed to the repo and will be fetched during installation."
