#!/bin/bash

echo "<openbox_pipe_menu>"

function endexit {
  echo '</openbox_pipe_menu>'
  exit
}

which xrandr 1>/dev/null || {
  echo '<item label="Error: xrandr is not installed">'
  endexit
}

displays=$(xrandr -q | egrep ' (connected|disconnected) ' | awk '{print $1}')

if [ -z "$displays" ]; then
  echo '<item label="Error: xrandr reports no displays.">'
  endexit
fi

for display in $displays; do
  echo "<item label=\"$display\"><action name=\"Execute\"><execute>"
  echo -n "   xrandr "
  for d in $displays; do
    if [ "$d" = "$display" ]; then
      echo -n "--output $d --primary --auto "
    else
      echo -n "--output $d --off "
    fi
  done
  echo -e "\n</execute></action></item>"
done

cat << END
<item label="All">
  <action name="Execute">
    <execute>xrandr --auto</execute>
  </action>
</item>
END

endexit
