#!/bin/bash
#
# eater@eater.org
#
# Openbox pipemenu for selecting displays via xrandr. Do something
# like this in your menu.xml:
#
#   <menu id="displays" label="Displays" execute="/path/to/this" />
#
# See also:
#   http://openbox.org/wiki/Help:Menus#Pipe_menus
#   http://wiki.debian.org/XStrikeForce/HowToRandR12
#   http://wiki.eater.org/ocd

echo "<openbox_pipe_menu>"

function endexit {
  echo '</openbox_pipe_menu>'
  exit
}

which xrandr 1>/dev/null || {
  echo '<item label="Error: xrandr is not installed">'
  endexit
}

displays=$(xrandr -q | egrep ' (connected|disconnected) ' | awk '{print $1}')

if [ -z "$displays" ]; then
  echo '<item label="Error: xrandr reports no displays.">'
  endexit
fi

for display in $displays; do
  echo -n "<item label=\"$display\"><action name=\"Execute\"><execute>xrandr"
  # Set $display auto/primary, set the others to off.
  for d in $displays; do
    if [ "$d" = "$display" ]; then
      echo -n "--output $d --primary --auto "
    else
      echo -n "--output $d --off "
    fi
  done
  echo -e "</execute></action></item>"
done

cat << END
<item label="All">
  <action name="Execute">
    <execute>xrandr --auto</execute>
  </action>
</item>
END

endexit
